export const WORK_LOCATION_OPTIONS = [
  'AMET',
  'Anantapur - Experience Center',
  'Annamacharya University',
  'Aurora University',
  'A Dy Patil University',
  'Bangalore - NxtWave Office',
  'BITS Chevella',
  'Brigade Towers: First Floor - East Wing',
  'Brigade Towers: Fourth Floor - East Wing',
  'Brigade Towers: Fourth Floor - West Wing',
  'Brigade Towers: Ground Floor - East Wing',
  'Brigade Towers: Second Floor - East Wing',
  'Chennai - NxtWave Office',
  'Chaitanya Deemed University',
  'CIET& CITY- Chalapathi',
  'Crescent University',
  'Delhi - NxtWave Office',
  'Isprout',
  'Jaipur - NxtWave Office',
  'Kapil Kavuri Hub - Fifth Floor',
  'Kapil Kavuri Hub - First Floor',
  'Kapil Kavuri Hub - Ninth Floor (ALT F)',
  'Kochi - NxtWave Office',
  'Malla Reddy Vishwavidyapeeth',
  'Noida International University',
  'NRI',
  'NSRIT',
  'Pune - Experience Center',
  'Ramky Selenium',
  'Sanjay Godhawat University',
  'Sohini Techpark',
  'S-Vyasa University',
  'Takshasila University',
  'Tirupati - Experience Center',
  'Vijayawada - Experience Center',
  'Vivekananda Global University',
  'WeWork Raja Pushpa Summit',
  'Work From Home',
  'Yenepoya',
]


