export const WORK_LOCATION_OPTIONS = [
  'Brigade Towers: Ground Floor - East Wing',
  'Brigade Towers: First Floor - East Wing',
  'Brigade Towers: Second Floor - East Wing',
  'Brigade Towers: Fourth Floor - East Wing',
  'Brigade Towers: Fourth Floor - West Wing',
  'Kapil Kavuri Hub - First Floor',
  'Kapil Kavuri Hub - Fifth Floor',
  'Kapil Kavuri Hub - Ninth Floor (ALT F)',
  'iSprout',
  'Sohini Techpark',
  'Pune - Experience Center',
  'Bangalore - NxtWave Office',
  'Chennai - NxtWave Office',
  'The Hive',
  'AMET',
  'Annamacharya University',
  'CIET & CITY - Chalapathi',
  'Delhi - NxtWave Office',
  'Jaipur - NxtWave Office',
  'Yenepoya',
  'Vijayawada - Experience Center',
  'Tirupati - Experience Center',
  'Kadapa - Experience Center',
  'Anantapur - Experience Center',
  'Noida International University',
  'Vivekananda Global University',
  'A Dy Patil University',
  'Sanjay Ghodawat University',
  'S-Vyasa University',
  'Crescent University',
  'Takshasila University',
  'NRI',
  'NSRIT',
  'Chaitanya Deemed University',
  'BITS',
  'Malla Reddy Vishwavidyapeeth',
  'Aurora University',
  'BITTS Bilani University',
  'KFinTech',
  'Office - We Work',
]


